### ISSUE TITLE
1.21 port ? :)

### ISSUE THREAD

**Issue by jinkhya** [Thomilist/dimensional-inventories#12]
Hello ! 
Your mod is exactly what I was looking for for our new playthrough on our community servers. I was wondering if you could update it to 1.21. I dunno how much work it is and ofc IRL comes first so if you don't have the time for it at this moment I completely understand. I'm just seeing if you plan on updating it soon - ish :)

Best regards, 
Jin

**Comment by Thomilist** [comment]
Hi!

Thank you for the kindness. Updating to 1.21 is very much my intention. I'm almost done with a big overhaul of the internals, but like you say, real life has slowed the process. But still, I don't see a reason for 1.21 compatibility to be a significant hurdle, so "soon-ish" seems about right :)

**Comment by jinkhya** [comment]
Sounds good ! I'll wait patiently then no worries, thanks for the feedback ! :)

**Comment by Saxostevesaxo** [comment]
love the mod :) thanks for the update! (when it is released)

**Comment by Thomilist** [comment]
Quick status update: I have made good progress on the rewrite, and I'm hoping for a release some time next week.

I'd say it's a significant (and much-needed) step up in code quality, which should make future updates much quicker and easier. In terms of features, nothing is lost, and a few minor "quality-of-life" changes are included. Existing (old) data will be migrated fully automatically just by starting the server with the new version installed.

~~Note to self: Always think about versioning when storing persistent data.~~

**Comment by Thomilist** [comment]
Good news! I have finished the rewrite and have ported to 1.21 - [it is finally out](https://github.com/Thomilist/dimensional-inventories/releases/tag/2.0.0%2B1.21)!

Of course, since so much has changed behind the scenes, I'd strongly recommend backing up your worlds before updating. As previously mentioned, migration is automatic, so it *should* Just Work™, but you never know. I do of course test it, but there are bound to be edge cases out in the wild that I've missed, so don't hesitate to let me know if something isn't working quite right.

Big thank you for all the kindness as well! I don't currently run a server myself or even play Minecraft all that much, but knowing that people enjoy the mod and seeing all the pleasant comments and requests is *very* motivating. ❤

**Comment by ScorNinja** [comment]
So haven't yet tested the new 1.21 port, but wanted to bring to your attention an exploit someone on our server figured out and abused:

Sending a minecart storage container (chest/hopper) through the end will destroy the minecart but drop all the items into the end which allows them to bring items between dimensions.

**Comment by Thomilist** [comment]
> Sending a minecart storage container (chest/hopper) through the end will destroy the minecart but drop all the items into the end which allows them to bring items between dimensions.

Welp, that's a pretty straight-forward exploit. Easy bug to reproduce, though, so I've added an issue for it: #15.
