### ISSUE TITLE
Crash when entering unconfigured dimension

### ISSUE THREAD

**Issue by SlyAquaGuy** [Thomilist/dimensional-inventories#3]
Hey! I've been loving the mod so far, it's perfect for what I'm trying to do on my server; however the mod tends to crash the game whenever a player tries to enter an unconfigured dimension.

This tends to happen quite a bit while using replaymod but also happens when I add custom dimensions and attempt to join them without adding them using the /diminv command.

Logs attached, and thanks for creating such a useful mod for fabric!
[2023-04-28-7.log.gz](https://github.com/Thomilist/dimensional-inventories/files/11357661/2023-04-28-7.log.gz)

**Comment by Thomilist** [comment]
Hello!

I think I've been able to reproduce and fix the crashing. Would you mind trying out the version linked below and letting me know if the issue is resolved?

[dimensional-inventories-1.0.2pre1+1.19.4 (UNZIP).zip](https://github.com/Thomilist/dimensional-inventories/files/11361652/dimensional-inventories-1.0.2pre1%2B1.19.4.UNZIP.zip)

Thank you for you kind words :)

**Comment by SlyAquaGuy** [comment]
Hey! I did a bit of testing and all the cases in which the mod caused a crash seem to be fixed. Love the streamlined implementation as well, it's nice to be able to use the default inventory pool without it automatically being assigned. 

Stay safe out there, thanks again for making this mod :)

**Comment by Thomilist** [comment]
Nice. I have worked the fix into a new set of releases. The only difference between 1.0.2pre1+1.19.4 and 1.0.2+1.19.4 is a minor formatting fix in some log messages. 

Thank you very much for the feedback and kindness, and have a good one :)
