### ISSUE TITLE
Need help with the creative world datapack.

### ISSUE THREAD

**Issue by KominoStyle** [Thomilist/dimensional-inventories#7]
[Creative_Dimension_1.20.2.zip](https://github.com/Thomilist/dimensional-inventories/releases/download/1.0.2%2B1.20.2/Creative_Dimension_1.20.2.zip) i wanted to use this datapack from your list, but i dont get it how i can create the world/ join the creative world

**Comment by Thomilist** [comment]
No worries, I'll try my best to help you out. Not 100% sure how far along you are, so I might include a few things you've already done.

I assume you already have your normal world, either singleplayer or on a server, and that you have downloaded the `Creative_Dimension_1.20.2.zip` datapack.

Find your world folder. For a singleplayer world, that's usually under `%appdata%/.minecraft/saves`. For a server, it will typically be a folder named `world` at the root of your server folder.

Inside the world folder, there should be a folder named `datapacks` - if not, create it. Then, unzip `Creative_Dimension_1.20.2.zip` to this folder. Your folder structure should look something like `<worldname>/datapacks/Creative_Dimension`.

Open the world in Minecraft (if it's already open, that should be okay too). The command `/datapack list` should show a datapack called `file/Creative_Dimension (world)`. If it's available, but not enabled, you can enable it with `/datapack enable "file/Creative_Dimension`.

To get to the creative dimension, you will need some kind of teleport command. The vanilla `tp` command can do the trick when combined with the `execute` command to specify the dimension, e.g.:

`/execute in custom:creative run tp 0 70 0`

And likewise to get back to the overworld:

`/execute in minecraft:overworld run tp 0 70 0`

This is a bit clunky in the long run, which is why I recommend using a mod such as [Essential Commands](https://modrinth.com/mod/essential-commands). That would give you the ability to set a spawn, warps and homes, as well as the `/back` command, which is very convenient for quickly switching back and forth between survival and creative. Personally, I like to create a warp to act as the creative dimension spawn point, and then allowing each player to set a home in the creative world for their own use.

In the future, I'd like to add some or all of these features into the mod itself so you don't need multiple mods just to get started.

Does that solve your problem?

**Comment by KominoStyle** [comment]
Ah okay with the execute command, nice that's good to know, thank you ♥

also is it possible to have a nether/end for the creative world it self? because the reason why i wanted to create this is so user can test what the wanna build and there are many redstone farms that works via nether and so. if its not possible for it than that's fine too, im really happy that the creative world works, and with you mod also to keep the inventory ♥

**Comment by Thomilist** [comment]
Hmm, yes and no.

The dimensions themselves can be added with a different datapack. Here's one that adds `custom/overworld`, `custom/the_nether` and `custom/the_end`: [Dimensions_OverworldNetherEnd_1.20.2.zip](https://github.com/Thomilist/dimensional-inventories/files/13663762/Dimensions_OverworldNetherEnd_1.20.2.zip)

Within each dimension, most things work as expected, with the exception of the enderdragon fight and portal creation. The enderdragon does not spawn, so there's no exit portal, and nether portals cannot be lit with fire.

Unfortunately, custom dimensions implemented only with datapacks do not support portals. For single-dimension builds, that's no issue, but if you want to do things like chunk loading (which it sounds like you do), neither vanilla Minecraft nor Dimensional Inventories can help. 

There's [a post on the feedback hub](https://feedback.minecraft.net/hc/en-us/community/posts/360077184371-Define-nether-portal-destinations-in-custom-dimension-types) requesting this feature, but for now, maybe try adding [Dimension Portal Linker](https://github.com/Encrypted-Thoughts/DimensionPortalLinker/). I haven't tested it myself, but it seems like it solves exactly this problem, and I don't see a reason for it to be incompatible with Dimensional Inventories.

**Comment by KominoStyle** [comment]
Oh, nice! I couldn't find this mod on Modrinth, sadly. Thanks to you, I just took the Nether and End, and the Creative one I already created. With the Dimension Portal Linker, it works perfectly! Now my friends can also go to the creative world and test redstone builds/farms, as the Nether and End now work for the creative world.

You were really helpful to me. Thank you a lot! ♥

**Comment by Thomilist** [comment]
You're welcome! I'm glad to hear it all works :)
